name: Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - run: npm ci

      - run: npm run package

      - run: npm run lint

      - run: npx playwright install-deps

      - run: xvfb-run -a npm test
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: test-result
          path: test-results/
          retention-days: 2
